# Base runtime 
image: docker:latest
# Docker as a service
services:
    - docker:dind
# Stages declaration (add names as required)
stages:
    - build

# Pack stage (docker build)
build:
    stage: build
    script:
        - apk add --update nodejs-npm
        - npm install -g @angular/cli
        - npm install
        - ng build
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:latest .
        - docker push $CI_REGISTRY_IMAGE:latest
