sudo: true
dist: trusty
language: node_js
node_js:
  - "7"

before_script:
- npm install -g @angular/cli
- npm install

script:
- ng build
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t vice-webui:latest .
- docker tag vice-webui:latest viceregistry/vice-webui:latest
- docker images
- docker push viceregistry/vice-webui:latest
- pwd; ls -lah

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: master